apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: express-mobile-ui

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: express-mobile-ui
  version: v1.0.0

images:
- name: express-mobile-ui
  newTag: latest
