apiVersion: v1
kind: Service
metadata:
  name: express-mobile-ui-service
  namespace: express-mobile-ui
  labels:
    app: express-mobile-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: express-mobile-checkin
